volumes:
    static: {}
    postgres_data: {}
    django_cache: {}

networks:
    default:
        external: true
        name: web


services:

    database:
        image: postgres:alpine
        environment:
            POSTGRES_USER: dryorm
            POSTGRES_PASSWORD: dryorm
            POSTGRES_DB: dryorm
        volumes:
            - postgres_data:/var/lib/postgresql/data

    nginx:
        build: ./webserver/
        image: dryorm/nginx
        volumes:
            - static:/app/static
        ports:
            - 80
        depends_on:
            - backend
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.nginx.rule=Host(`dryorm.d.xterm.info`)"

    redis:
        image: redis:7.4-alpine

    backend:
        build: ./backend/
        image: dryorm/backend
        volumes:
            - ./backend:/app
            - static:/app/static
            - django_cache:/app/cache
        depends_on:
            - database
            - redis
        ports:
            - 8000
        # command: python manage.py runserver 0.0.0.0:8000
        env_file: .env

    rq_worker:
        image: dryorm/backend
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./backend:/app
            - django_cache:/app/cache
        depends_on:
            - redis
            - backend
        command: rq worker --url redis://redis:6379
        env_file: .env

    rq_dashboard:
        build: ./rq-dashboard/
        image: dryorm/rq-dashboard
        depends_on:
            - redis
        ports:
            - 9181:9181
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.rq-dashboard.rule=Host(`rq.dryorm.d.xterm.info`)"

    # Executors

    executor-python-django:
        build: ./executors/python-django
        image: dryorm-executor/python-django
        command: /bin/true

            # executor-python-peewee:
            #     build: ./executors/python-peewee
            #     image: dryorm-executor/python-peewee
            #     command: /bin/true

            # executor-python-sqlalchemy:
            #     build: ./executors/python-sqlalchemy
            #     image: dryorm-executor/python-sqlalchemy
            #     command: /bin/true

    # executor-php-eloquent:
    #     build: ./executors/php-eloquent
    #     image: dryorm-executor/php-eloquent
    #     command: /bin/true
