#!/bin/bash

SERVICE_DB_HOST=${1:-$SERVICE_DB_HOST}
SERVICE_DB_PORT=${2:-$SERVICE_DB_PORT}
SERVICE_DB_USER=${3:-$SERVICE_DB_USER}
SERVICE_DB_PASSWORD=${4:-$SERVICE_DB_PASSWORD}
DB_NAME=${5:-$DB_NAME}
DB_USER=${6:-$DB_USER}
DB_PASSWORD=${7:-$DB_PASSWORD}

mysql -h $SERVICE_DB_HOST -P $SERVICE_DB_PORT -u root -p$SERVICE_DB_PASSWORD <<SQL
-- Drop database and user if they exist
DROP DATABASE IF EXISTS \`$DB_NAME\`;
DROP USER IF EXISTS \`$DB_USER\`@\`%\`;

-- Create fresh database and user
CREATE DATABASE \`$DB_NAME\`;
CREATE USER \`$DB_USER\`@\`%\` IDENTIFIED BY '$DB_PASSWORD';

-- Grant access to only this DB
GRANT ALL PRIVILEGES ON \`$DB_NAME\`.* TO \`$DB_USER\`@\`%\`;

-- Flush privileges to apply changes
FLUSH PRIVILEGES;

SQL 

