# Generated by Django 5.2 on 2025-05-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('code', models.TextField()),
                ('result', models.TextField(blank=True)),
                ('created', models.DateField(auto_now=True)),
                ('private', models.BooleanField(default=False)),
            ],
        ),
    ]
