# Generated by Django 5.2.1 on 2025-05-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dryorm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='database',
            field=models.CharField(default='sqlite', max_length=50),
        ),
    ]
