# Generated by Django 5.2.1 on 2025-05-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dryorm', '0002_snippet_database'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
