# Generated by Django 5.2.5 on 2025-11-10 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dryorm', '0003_alter_snippet_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='django_version',
            field=models.CharField(default='5.2.8', max_length=20),
        ),
    ]
