# Generated by Django 5.2.5 on 2025-12-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dryorm', '0004_snippet_django_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='orm_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='snippet',
            name='ref_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='snippet',
            name='ref_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
