# Generated by Django 5.2.5 on 2025-12-26 10:20

from django.db import migrations


def migrate_version_forward(apps, schema_editor):
    """Convert django_version to orm_version format for existing records."""
    Snippet = apps.get_model('dryorm', 'Snippet')
    for snippet in Snippet.objects.filter(orm_version__isnull=True):
        if snippet.django_version:
            # Handle case where django_version already has prefix
            if snippet.django_version.startswith('django-'):
                snippet.orm_version = snippet.django_version
            else:
                snippet.orm_version = f"django-{snippet.django_version}"
            snippet.save(update_fields=['orm_version'])


def migrate_version_backward(apps, schema_editor):
    """Convert orm_version back to django_version format."""
    Snippet = apps.get_model('dryorm', 'Snippet')
    for snippet in Snippet.objects.filter(orm_version__isnull=False):
        if snippet.orm_version and snippet.orm_version.startswith('django-'):
            snippet.django_version = snippet.orm_version.replace('django-', '')
            snippet.save(update_fields=['django_version'])


class Migration(migrations.Migration):

    dependencies = [
        ('dryorm', '0005_add_version_fields'),
    ]

    operations = [
        migrations.RunPython(migrate_version_forward, migrate_version_backward),
    ]
