# Generated by Django 5.2.5 on 2025-12-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dryorm', '0006_migrate_version_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='sha',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
