# Generated by Django 5.2.5 on 2025-12-31 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dryorm', '0007_add_sha_to_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
