# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('models_code', models.TextField()),
                ('transactions_code', models.TextField()),
                ('framework', models.CharField(max_length=100)),
                ('created', models.DateField(auto_now=True)),
            ],
        ),
    ]
