# Generated by Django 5.2 on 2025-04-28 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='transactions_code',
        ),
    ]
